# for development only
version: "3"
services:
  minio:
    image: minio/minio
    container_name: micro_s3
    restart: unless-stopped
    command: server /data
    environment:
      - MINIO_ACCESS_KEY=YOUSHALLNOTPASSKEY
      - MINIO_SECRET_KEY=YOUSHALLNOTPASSSECRET
    ports:
      - 9000:9000
  postgres:
    image: postgres:12-alpine
    container_name: micro_postgres
    restart: unless-stopped
    ports:
      - 127.0.0.1:5433:5432
    environment:
      - POSTGRES_USER=micro
      - POSTGRES_PASSWORD=youshallnotpass
      - POSTGRES_DB=micro
    volumes:
      - micro_postgres:/var/lib/postgresql/data

volumes:
  micro_postgres: {}
